fancyhotel/booking/urls.py
#from django.urls import path
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('minside/', views.booking_overview, name='min side'),
    
    path('room/', views.getRooms, name='search rooms'),
    path('room/<int:roomNr>/booking', views.roombooking, name='roombooking'),

    path('thanks/', views.thanks, name='thanks'),

    #eks: /booking/room/101/
    path('room/<int:roomNr>/', views.room, name='room info'),

    #booking/login gir login siden
    path('login/', views.login_user, name='logg inn'),
    path('logout/', views.logout_user, name='logg ut'),

    #gir registrer siden 
    path('login/booking/signup_test.html', views.signup_user, name="sign up"),

    #booking/roomoverview gir romoversikt siden
    path('roomoverview/', views.roomoverview, name='roomoverview'),

    path('about/', views.about, name='about'),

    # Cleaning information
    path('cleaning/', views.cleaning_index, name='cleaning-index'),
    path('cleaning/lastCleaned', views.cleaning_last_cleaned, name='cleaning-last-cleaned'),
    path('cleaning/clean', views.cleaning_clean, name='cleaning-clean'),
    path('cleaning/<int:NUMBER_OF_DAYS>', views.cleaning, name='cleaning'),

    #test-shit
    #path('signup_test/', views.signup_user, name="signup_test"),
    #path('login_test/', views.login_user, name="login_test")


]

fancyhotel/fancyhotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('booking/', include('booking.urls')),
    path('admin/', admin.site.urls),
]

fancyhotel/booking/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.conf import settings
from django.utils import timezone

# Create your models here.

########################### HOTELROOM ###########################
class Hotelroom(models.Model):
    roomNumber = models.IntegerField(unique=True,
                                    validators=[MinValueValidator(101,message="Room number must be three digits (i.e. 101)")])
    numberOfBeds = models.IntegerField()
    pricePrNight = models.IntegerField()
    singleBeds = models.IntegerField(default=0)
    includedBreakfast = models.BooleanField(default = True)
    includedParking = models.BooleanField(default = True)
    includedCancelling = models.BooleanField(default = False)
    smokingAllowed = models.BooleanField(default = False)
    lastCleaned = models.DateTimeField(verbose_name='Last cleaned', default=timezone.now)

    created = models.DateTimeField(verbose_name='Created', auto_now_add=True)

    @property
    def doubleBeds(self):
        return (self.numberOfBeds - self.singleBeds) / 2

    @property
    def floor(self):
        return int(str(self.roomNumber)[0])

    def cleanRoom(self):
        self.lastCleaned = timezone.now()
        self.save()

    class Meta:
        ordering = ['roomNumber']

    def __str__(self):
        return F"{self.roomNumber}"



########################### CUSTOMER ###########################
class Customer(models.Model):
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=40)
    email = models.EmailField(unique=True)
    phoneNr = models.CharField(max_length=8)

    class Meta:
        ordering = ['lastName', 'firstName']

    def __str__(self):
        return F"{self.lastName},  {self.firstName}"



# ########################### CUSTOM_USER ###########################
# Commented out for now, as I am to tired to implement it properly
# For more information, see comments at forms.UserCreateForm
# class custom_user(models.AbstractBaseUser):
#     first_name = models.CharField(max_length=20)
#     last_name = models.CharField(max_length=40)
#     email = models.EmailField(unique=True)
#     phone_number = models.CharField(max_length=8)

#     USERNAME_FIELD = 'email'
#     EMAIL_FIELD = 'email'
#     REQUIRED_FIELDS = ['first_name', 'last_name']

#     def is_active(self):
#         return True

#     def get_full_name(self):
#         return __str__(self)

#     def get_short_name(self):
#         return self.first_name

#     class Meta:
#         ordering = ['lastname', 'firstname']
    
#     def __str__(self):
#         return F"{self.last_name}, {self.first_name}"



########################### BOOKING ###########################
class Booking(models.Model):
    room = models.ForeignKey(Hotelroom, on_delete=models.PROTECT)
    customerID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=40)
    email = models.EmailField()
    phoneNr = models.CharField(max_length=8, null=True, blank=True)
    dateStart = models.DateField(verbose_name="Start date")
    dateEnd = models.DateField(verbose_name="End date")

    class Meta:
        ordering = ['dateStart', 'dateEnd', 'room']


    def clean(self):
        """Ensure startDate > endDate
        and that the room has not been booked in the same time period"""

        if self.dateEnd <= self.dateStart:
            raise ValidationError("Start date must be before end date!")
        
        # If there are bookings in the database with:
        # - same room__id
        # - different booking__id
        # - first date at or after dateStart (but before dateEnd)
        # - last date at or before dateEnd (but after dateStart)
        # Raise ValidationError
        if Booking.objects.filter(room__id=self.room_id).exclude(pk=self.pk).filter(
                Q(dateEnd__gt=self.dateStart, dateStart__lt=self.dateEnd)
                ).exists():
            raise ValidationError("Overlapping dates, room has been booked.")


    def __str__(self):
        return F"Room {self.room}: {self.dateStart} - {self.dateEnd}"



########################### BOOKING PROXY ###########################
class BookingOverview(Booking):
    """Proxy of Booking, to use for admin.overview"""
    class Meta:
        proxy = True

    verbose_name = 'Booking Overview'
    verbose_name_plural = 'Booking Overview'

fancyhotel/booking/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse
from .models import Hotelroom, Booking
from .forms import SearchForm, BookingForm, UserCreateForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from datetime import date, datetime, timedelta
from django.core.mail import send_mail
from django.conf import settings

from users.models import CustomUser 

from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.response import TemplateResponse
from django.contrib import messages


def index(request):
    return render(request, 'booking/index.html')



def thanks(request):
    context = {
        'roomNr' : request.session.get('roomNr'),
        'startDate' : request.session.get('startDate'),
        'endDate' : request.session.get('endDate'),
        }
    sendemail(request)

    return render(request, 'booking/thanks.html', context)


def sendemail(request):
    subject = 'Bookingbekreftelse'
    message = 'Takk for at du booket rom ' + str(request.session.get('roomNr')) + ' den ' + str(request.session.get('startDate')) + ' - ' + str(request.session.get('endDate'))
    email_from = settings.EMAIL_HOST_USER
    try:
        recipient_list = [request.user.email, ]
        send_mail(subject, message, email_from, recipient_list)
    except:
        recipient_list_guest = [request.session['email'], ]
        send_mail(subject, message, email_from, recipient_list_guest)




def roombooking(request, roomNr):
     # If method == POST - process form data
    if request.method == 'POST':
        # request.POST is immutable, so we have to create an updated request in order to add dates
        # For this, I refer to this, which is where I found the recipe:
        # https://stackoverflow.com/questions/18534307/change-a-form-value-before-validation-in-django-form/49296068
        updated_request = request.POST.copy()

        # Set room from URL
        updated_request.update({'room' : Hotelroom.objects.get(roomNumber=roomNr)})

        # Set dateStart and dateEnd from session variables (if applicable)
        if request.session.get('startDate', None) != None:
            dateStart = datetime.strptime(request.session['startDate'], "%Y-%m-%d").date()
            updated_request.update({'dateStart' : dateStart})
        if request.session.get('endDate', None) != None:
            dateEnd = datetime.strptime(request.session['endDate'], "%Y-%m-%d").date()
            updated_request.update({'dateEnd' : dateEnd})

         # Check if name or email has changed. If not, ensure it is user first_ and last_name and email
        if request.user.is_authenticated:
            #global email
            email = request.user.email
            firstName = request.user.first_name
            lastName = request.user.last_name
            phoneNr = request.user.phone_number

            if updated_request['email'] in [None, '']:
                updated_request.update({'email' : email})
            if updated_request['firstName']  in [None, '']:
                updated_request.update({'firstName' : firstName})
            if updated_request['lastName']  in [None, '']:
                updated_request.update({'lastName' : lastName})
            if updated_request['phoneNr']  in [None, '']:
                updated_request.update({'phoneNr' : phoneNr})

        # Create a SearchForm, populate it with data
        form = BookingForm(updated_request)

        # Check if valid
        if form.is_valid():
            # Process data (return Query)
            request.session['roomNr'] = roomNr
            request.session['email'] = form.cleaned_data['email']
            request.session['firstName'] = form.cleaned_data['firstName']
            request.session['lastName'] = form.cleaned_data['lastName']
            request.session['phoneNr'] = form.cleaned_data['phoneNr']

            if request.user.is_authenticated:
                booking = form.save(commit=False)
                booking.customerID = request.user   # Set Booking.CustomerID = logged in user
                booking.save()
            
            else:
                form.save()

                if 'submit_and_register' in request.POST:
                    sendemail(request)
                    return HttpResponseRedirect(reverse('sign up'))

            return HttpResponseRedirect(reverse('thanks'))
    
    # else (GET or other method) - create blank form
    else:
        form = BookingForm()

        # Lock room Number
        form.fields['room'].disabled = True
        form.fields['room'].initial = Hotelroom.objects.get(roomNumber=roomNr)

        # Lock dates
        if request.session.get('startDate', None) != None:
            form.fields['dateStart'].disabled = True
            dateStart = datetime.strptime(request.session['startDate'], "%Y-%m-%d").date()
            form.fields['dateStart'].initial = dateStart
        if request.session.get('endDate', None) != None:
            form.fields['dateEnd'].disabled = True
            dateEnd = datetime.strptime(request.session['endDate'], "%Y-%m-%d").date()
            form.fields['dateEnd'].initial = dateEnd

        # If user is logged in / authenticated - populate fields with name and email
        if request.user.is_authenticated:
            form.fields['email'].initial = request.user.email
            form.fields['firstName'].initial = request.user.first_name
            form.fields['lastName'].initial = request.user.last_name
            form.fields['phoneNr'].initial = request.user.phone_number

    
    # At this point, form is either filled-but-invalid or empty. Either way, it can be rendered
    return render(request, 'booking/roombooking.html', {'form': form})



#def login(request):
    #return render(request, 'booking/login.html')



def roomoverview(request):
    return render(request, 'booking/roomoverview.html')



def about(request):
    return render(request, 'booking/about.html')



# Test for å sjekke om bruker er cleaning:
def check_cleaning(user):
    return user.is_cleaner

@login_required()
@user_passes_test(check_cleaning, login_url='', redirect_field_name=None)
def cleaning_index(request):
    return TemplateResponse(request, 'booking/cleaning_index.html')

@login_required()
@user_passes_test(check_cleaning, login_url='', redirect_field_name=None)
def cleaning(request, NUMBER_OF_DAYS):
    """
        A view, rendering an HTML-table with rooms as rows and days as columns

            
        Example of busy_dates, using NUMBER_OF_DAYS = 7:
            busy_dates == {
                101 : [None, None, None, booked, booked, None, None],
                102 : [None, None, booked, None, booked, None, None],
                ...
            }

        An anonymized version of admin.overview
    """

    busy_dates = {}
    header_row_dates = []
    today = date.today()
    end_of_period = today + timedelta(NUMBER_OF_DAYS - 1)

    rooms = Hotelroom.objects.all()
    
    # Create header-row
    for i in range(NUMBER_OF_DAYS):
        _date = today + timedelta(i)
        header_row_dates.append(str(_date.day) + '/' + str(_date.month))

    # Fill busy_dates with NUMBER_OF_DAYS bolean values
    for room in rooms:
        busy_dates[room.roomNumber] = [None] * NUMBER_OF_DAYS

    # Find all bookings in time period:
    bookings = Booking.objects.filter(dateEnd__gte=today).filter(
        Q(dateEnd__lte=end_of_period) | Q(dateStart__lt=end_of_period))

    # Go through bookings, 
    for booking in bookings:
        start_index = (booking.dateStart - today).days
        end_index = (booking.dateEnd - today).days

        if start_index < 0:
            start_index = 0
        if end_index > NUMBER_OF_DAYS:
            end_index = NUMBER_OF_DAYS

        """ Adds a booking to busy_dates. The overview shows each booking starting the day the customer
        arrives, and then have length = as many nights as the customer stays. This means that blank days can always 
        be cleaned after a set checkout-time, while the cleaning the first day of a booking must be done before
        a set checkin-time.
        """
        for i in range(start_index, end_index):
            busy_dates[booking.room.roomNumber][i] = 'booked'

    context = dict(
        # Fill in values here
        header_row_dates = header_row_dates,
        busy_dates = busy_dates,
        weekdays_until_saturday = 6 - today.weekday(),
        weekdays_until_sunday = 7 - today.weekday(),
    )

    return TemplateResponse(request, 'booking/cleaning.html', context)



def room(request, roomNr):
    room = Hotelroom.objects.get(roomNumber=roomNr)
    context = {'room': room,}
    return render(request, 'booking/room.html', context)

def booking_overview(request):
    if request.user.is_authenticated:
        current_user = request.user
        booking = Booking.objects.filter(email = current_user.email)

        personal_info = CustomUser.objects.filter(email = current_user.email)
        context = {
        'info': personal_info,
        'bookings': booking
        }
    else:
        context = {

        }
    return render(request, "booking/minside.html", context)

def getRooms(request):
    """
    Gives a form to search and filter rooms.

    Advanced filtering is inspired by: https://stackoverflow.com/a/16779396
    """
    context = dict()

    # If method == POST - process form data
    if request.method == 'POST':

        # Create a SearchForm, populate it with data
        form = SearchForm(request.POST)
        context['form'] = form

        # Check if valid
        if form.is_valid():
            # Process data (return Query)
            startDate = form.cleaned_data['startDate']
            endDate = form.cleaned_data['endDate']
            minNumberOfBeds = form.cleaned_data['minNumberOfBeds']

fancyhotel/booking/templates/booking/about.html
{% extends 'booking/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Forside{% endblock %}</title>
</head>
<body>
    {% load static %} 
    {% block header %}
    <link rel="stylesheet" href="{% static "css/about.css" %}">
    <!-- slideshow header -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="header-bilde" class="d-block w-100" src="{% static "img/front.jpeg" %}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="header-bilde" class="d-block w-100" src="{% static "img/restaurant__.jpeg" %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="header-bilde" class="d-block w-100" src="{% static "img/breakfast.jpeg" %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      {% endblock %}

      
      {% block content %}
      <br><br>
      <!-- velkommen tekstboks -->
      
      <div class="textbox_left">
        <h1>Velkommen</h1>
        <p>Du har nå kommet frem til Skikkelig Fancy Hotell sin nettside. Her vil du finne informasjon om hotellet, se bilder og kunne bestille rom</p>
      </div>

      <img class="bilde" src="{% static "img/uteservering.jpeg" %}">
    

     

      <!-- kart og lokasjon -->
      <div class="mapbox" width="auto">
        <h1>Lokasjon</h1>
        <p>Hotellet befinner seg i Trondheim sentrum. Her bor du i nærheten av en rekke kulturopplevelser, shoppingmuligheter og et stort utvalg av ulike restuaranter og kaféer</p>
        <div class="mapouter"><div class="gmap_canvas"><iframe width="800" height="253" id="gmap_canvas" src="https://maps.google.com/maps?q=olav%20trygvasonsgate%2011%20trondheim&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://periodic-table-of-elements.net"></a></div><style>.mapouter{position:relative;text-align:right;height:253px;width:800px;max-width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:253px;width:800px;max-width:100%;}</style></div>
      </div>
     
      <br><br>
      {% endblock %}
    
</body>
</html>

fancyhotel/booking/templates/booking/cleaning.html
{% extends "booking/cleaning_index.html" %}

{% block overview %}
<style>
    .overview-table-wrapper{
        display: block;
        overflow-x: auto;
        white-space: nowrap;
        width: 90%; /* Fallback, if needed */
        width: calc(100% - 5em);
    }
    .overview-table, .overview-col-first{
        color: #333;
        border-color: #707070;
    }
    .overview-header{
        font-weight: bold;
        background-color: #f9f9f9;
    }
    .overview-col-first{
        float: left;
        width: 5em;
        border-right: 1px solid #f9f9f9;
        text-align: left;
    }
    .overview-row:nth-child(even){
        background-color: #fff;
    }
    .overview-row:nth-child(odd){
        background-color: #f9f9f9;
    }
    .overview-row{
        color: black;
        font-weight: normal;
    }
    .overview-row:hover{
        font-weight: bold;
    }
    .overview-cell{
        width: 40px;
        padding: 10px;
    }
    .overview-cell-booked{
        background-color: red !important;
    }
    .overview-table th:nth-child(7n + {{ weekdays_until_saturday }}),
    .overview-table td:nth-child(7n + {{ weekdays_until_saturday }}),
    .overview-table th:nth-child(7n + {{ weekdays_until_sunday }}),
    .overview-table td:nth-child(7n + {{ weekdays_until_sunday }}){
        background-color:rgba(61, 61, 61, 0.05);
    }
</style>

<body>
    <h1>Booking overview</h1>

      <!--First column, as its own table, to simplify horizontal scrolling-->
      <table class="overview-col-first">
        <!--Header-->
        <tr class="overview-header"><th class="overview-cell">Room</th></tr>

        <!--Content-->
        {% for key, value in busy_dates.items %}
            <tr class="overview-row"><td style="padding-left: 10px;">{{ key }}</td></tr>
        {% endfor %}
    </table>

    <!--Rest of table-->
    <div class=overview-table-wrapper style="float: left;">
    <table class="overview-table">
        <!--Header-->
            <tr class="overview-header">
                {% for date in header_row_dates %}
                    <th class="overview-cell">{{ date }}</th>
                {% endfor %}
            </tr>

        <!--Content-->
        {% for key, value in busy_dates.items %}
            <tr class="overview-row">
                {% for status in value %}
                    {% if status == None %}
                        <td style="text-align: center;">-</td>
                    {% else %}
                        <td class="overview-cell-booked"></td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
    </div>   
</body>
{% endblock %}

fancyhotel/booking/templates/booking/cleaning_index.html
{% extends "booking/base.html" %}

{% block content %}
<style>
    .cleaning-overview-td{
        padding-left: 10px;
        padding-right: 10px;
        text-align: left;
    }
</style>

<body>
    <h1>Booking overview</h1>

    <p>
        Vennligst velg antall dager du vil se:
        <table>
            <td class="cleaning-overview-td"><a href="7">7</a></td>
            <td class="cleaning-overview-td"><a href="14">14</a></td>
            <td class="cleaning-overview-td"><a href="30">30</a></td>
            <td class="cleaning-overview-td"><a href="60">60</a></td>
            <td class="cleaning-overview-td"><a href="365">365</a></td>
        </table>
    </p>

    <h1>Cleaning information</h1>
    <p><a href="lastCleaned">Last cleaned</a></p>
</body>

{% block overview %}
{% endblock overview %}
{% endblock content %}

fancyhotel/booking/templates/booking/cleaning_last_cleaned.html
{% extends "booking/cleaning_index.html" %}

{% block overview %}

<body>
    <h1>Last cleaned</h1>

    <table>
        <tr>
            <th>Room</th>
            <th>Last cleaned</th>
            <th>Update</th>
        </tr>
        {% for room in rooms %}
        <tr>
            <td>{{ room.roomNumber }}</td>
            <td id='lastCleaned_{{room.roomNumber}}'>{{ room.lastCleaned | date:'F d, Y - H:i'}}</td>
            <td><button class='clean_button' id={{room.roomNumber}}>Clean</button></td>
        </tr>
        {% endfor %}
    </table>
</body>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
    /* Add listener, react on every button click */
    if (document.body.addEventListener){
        document.body.addEventListener('click',yourHandler,false);
    } else{
        document.body.attachEvent('onclick',yourHandler);//for IE
    }
    /* Function that runs when button is clicked */
    function yourHandler(e){
        e = e || window.event;
        var target = e.target || e.srcElement;
        if (target.className.match(/clean_button/))
        {
            var roomNumber = target.id;

            $.ajax({
                type: "POST",
                url: "{{ 'clean' }}",   /* URL is relative */
                data: {csrfmiddlewaretoken: '{{ csrf_token }}', roomNumber: roomNumber},   /* Passing room number to view */
                success:  function(response){
                    /* Update "Last cleaned"-cell to response (as given by view) */
                    document.getElementById("lastCleaned_".concat(roomNumber)).innerHTML = response;
                }
            });
        }
    }
</script>
{% endblock overview %}

fancyhotel/booking/templates/booking/index.html
{% extends 'booking/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

fancyhotel/booking/templates/booking/login_test.html
{% extends 'booking/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load static %} 

    {% block header %}
    <div>
        <img class="d-block w-100" src="{% static "img/front.jpeg" %}">
    </div>
    {% endblock %}


    {% load crispy_forms_tags %}
    {% block content %}
   
            
            <div class="container" id="content-container">
                <h1>Logg inn</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="hidden" name="next" value="{{ request.GET.next }}"/> <!-- fjerne?-->
                    <button type="submit" class="btn btn-secondary">Logg inn</button>
                </form>
                <br>
            <a href="booking/signup_test.html">Registrer deg her</a>
        </div>
        
   

    {% endblock %}
    
</body>
</html>

fancyhotel/booking/templates/booking/search.html
{% extends 'booking/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %} 
    <link rel="stylesheet" href="{% static "css/base.css" %}">  

    <title>Rombestilling</title>

</head>
<body>
    {% load static %} 
    {% block header %}
      <div>
        <img class="d-block w-100" src="{% static "img/front.jpeg" %}" alt="Third slide" height="400vh" style="overflow: hidden; object-fit: cover;">
      </div>
      {% endblock %} 

      {% load crispy_forms_tags %}
    {% block content %}

    <script>
      function more(obj) {
          var content = document.getElementById("showMore");
          
          if (content.style.display == "none") {
              content.style.display = "";
              obj.innerHTML = "Hide advanced options";
          } else {
              content.style.display = "none";
              obj.innerHTML = "Show advanced options";
          }
      }
    </script>


    <div class="container">
      <br><br>
  <h1>Bestill rom</h1>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                  {{ form.startDate|as_crispy_field }}
                </div>
                <div class="col-6">
                  {{ form.endDate|as_crispy_field }}
                </div>
              </div>
              {{ form.minNumberOfBeds|as_crispy_field }}
              {{ form.maxPricePrNight|as_crispy_field }}

              <a href="#" onclick="more(this);">Show advanced options</a>
              <div id="showMore"  style="display: none;">
                
                {{ form.singleBeds|as_crispy_field }}

              <div class='form-group'>
                <div id='div_id_includedBreakfast' class="form-check">
                  <input type="checkbox" name="includedBreakfast" class="checkboxinput form-check-input" id="id_includedBreakfast" checked="True">
                  <label for="id_includedBreakfast" class="form-check-label">
                    Breakfast included
                  </label>
                </div>
              </div>
              <div class='form-group'>
                <div id='div_id_includedParking' class="form-check">
                  <input type="checkbox" name="includedParking" class="checkboxinput form-check-input" id="id_includedParking" checked="True">
                  <label for="id_includedParking" class="form-check-label">
                    Parking included
                  </label>
                </div>
              </div>
              <div class='form-group'>
                <div id='div_id_includedCancelling' class="form-check">
                  <input type="checkbox" name="includedCancelling" class="checkboxinput form-check-input" id="id_includedCancelling">
                  <label for="id_includedCancelling" class="form-check-label">
                    Free cancelling included
                  </label>
                </div>
              </div>
              <div class='form-group'>
                <div id='div_id_smokingAllowed' class="form-check">
                  <input type="checkbox" name="smokingAllowed" class="checkboxinput form-check-input" id="id_smokingAllowed">
                  <label for="id_smokingAllowed" class="form-check-label">
                    Smoking allowed
                  </label>
                </div>
              </div>
              </div>

            <br>
            <!--<input type="submit" value="Submit">  -->
            <button type="submit" class="btn btn-success">Se tilgjengelighet</button>    
        </form>
        <br><br>
    </div>
    {% endblock %}
    
</body>
</html>